name: "✨ Feature Request"
description: "Propose a new feature or enhancement for the project."
title: "feat: [Brief description of the feature]"
labels: ["enhancement", "new-feature"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        # ⚠️ **IMPORTANT: AI Contributors Must Read First** ⚠️
        
        **Before proceeding with this feature request, AI contributors MUST review the complete guide at [`meta/CONTRIBUTING_ROBOTS.md`](../../meta/CONTRIBUTING_ROBOTS.md).**
        
        This guide contains essential information about your role, the required workflow, ADR review process, and the definition of a complete pull request.
        
        ---
        
        ## Feature Request Specification
  
  - type: textarea
    id: user-story
    attributes:
      label: "User Story"
      description: "Provide a clear, high-level goal from a user's perspective. This answers the 'why' behind the feature."
      placeholder: "As a [type of user], I want [to perform some action] so that [I can achieve some goal]."
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: "Acceptance Criteria"
      description: "Provide a checklist of specific, testable outcomes. The feature is done when all these boxes can be checked."
      value: |
        - [ ] GIVEN [a certain context] WHEN [an action is performed] THEN [this is the expected outcome].
        - [ ] 
    validations:
      required: true

  - type: textarea
    id: implementation-details
    attributes:
      label: "Implementation Details & Constraints"
      description: "Provide direct instructions, constraints, or expert guidance for the AI. Point to relevant ADRs or existing code."
      placeholder: "This must use the `nba_api` library. Adhere to ADR-004-pytest_testing. Do not make external network calls in this module."
    validations:
      required: false

  - type: checkboxes
    id: definition-of-done
    attributes:
      label: "Definition of Done"
      description: "Confirm that all steps for a completed feature have been considered."
      options:
        - label: "All acceptance criteria are met."
          required: true
        - label: "New code is accompanied by automated tests that pass."
          required: true
        - label: "Existing tests continue to pass."
          required: true
        - label: "The code adheres to the principles in `meta/DEVELOPMENT_PHILOSOPHY.md`."
          required: true
        - label: "All CI/CD checks are green."
          required: true
