name: "🔬 Strategic Plan & Discovery Request"
description: "Request a technical plan or research report. Output is documentation ONLY."
title: "plan: [High-level feature name]"
labels: ["planning", "discovery", "documentation"]
assignees: []
body:
  - type: markdown
    attributes:
      value: "## Strategic Planning Request"

  - type: textarea
    id: feature-idea
    attributes:
      label: "High-Level Feature Idea"
      description: "Describe your large or complex feature idea. Focus on the 'what' and 'why'."
      placeholder: "e.g., I want to add full support for WNBA stats, including ingestion, processing, and API endpoints."
    validations:
      required: true

  - type: textarea
    id: goals
    attributes:
      label: "Goals & Business Value"
      description: "What is the primary goal of this feature? What value does it add to the project?"
      placeholder: "e.g., To make Hoopstat Haus the most comprehensive data source for both NBA and WNBA stats."
    validations:
      required: true

  - type: textarea
    id: plan-deliverables
    attributes:
      label: "Requested Plan Deliverables (Documentation Only)"
      description: "The AI's response must be a document that delivers these items."
      value: |
        - [ ] A new Markdown file created in the `meta/plans/` directory containing the full analysis.
        - [ ] **Epic Breakdown:** A list of smaller, implementable User Stories derived from the high-level idea.
        - [ ] **Required ADRs:** A list of new ADRs that need to be proposed to support this feature.
        - [ ] **High-Level Implementation Strategy:** A description of the proposed technical approach, *without writing code*.
        - [ ] **Risks & Open Questions:** A list of potential risks, challenges, or open questions.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        ## ❗ Scope and Constraints
        **IMPORTANT:** The deliverable for this planning request is **documentation ONLY**.
        - **DO NOT** write or modify any application code in the `/apps` directory.
        - **DO NOT** implement CI/CD workflows in the `.github/workflows` directory.
        - The goal of this task is to produce the *plan* that will be used as the input for a future 'Feature Request'. Implementation will happen in a separate pull request.