name: "🔬 Strategic Plan & Discovery Request"
description: "Request a technical plan or research report. Output is documentation ONLY."
title: "plan: [High-level feature name]"
labels: ["planning", "discovery", "documentation"]
assignees: []
body:
  - type: markdown
    attributes:
      value: "## Strategic Planning Request"

  - type: textarea
    id: feature-idea
    attributes:
      label: "High-Level Feature Idea"
      description: "Describe your large or complex feature idea. Focus on the 'what' and 'why'."
      placeholder: "e.g., I want to add full support for WNBA stats, including ingestion, processing, and API endpoints."
    validations:
      required: true

  - type: textarea
    id: goals
    attributes:
      label: "Goals & Business Value"
      description: "What is the primary goal of this feature? What value does it add to the project?"
      placeholder: "e.g., To make Hoopstat Haus the most comprehensive data source for both NBA and WNBA stats."
    validations:
      required: true

  - type: textarea
    id: plan-deliverables
    attributes:
      label: "Requested Plan Deliverables (Documentation Only)"
      description: "The AI's response must be a document that delivers these items."
      value: |
        - [ ] A new Markdown file created in the `meta/plans/` directory containing the full analysis.
        - [ ] **High-Level Implementation Strategy:** A description of the proposed technical approach, *without writing code*.
        - [ ] **Required ADRs:** A list of new ADRs that need to be proposed to support this feature.
        - [ ] **Risks & Open Questions:** A list of potential risks, challenges, or open questions.
        - [ ] **🎯 ACTIONABLE FEATURE REQUESTS:** A "Next Steps" section with 5-10 copy-paste ready GitHub issue templates. Each should include:
          - Descriptive title following conventional commit format
          - Clear description of the deliverable
          - Specific acceptance criteria
          - Ready to copy-paste directly into new GitHub issues
        - [ ] **Phase-Based Implementation Roadmap:** Organize the feature requests into logical implementation phases (e.g., Phase 1: Foundation, Phase 2: Core Features, Phase 3: Advanced Features).
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        ## ❗ Scope and Constraints
        **IMPORTANT:** The deliverable for this planning request is **documentation ONLY**.
        - **DO NOT** write or modify any application code in the `/apps` directory.
        - **DO NOT** implement CI/CD workflows in the `.github/workflows` directory.
        - The goal of this task is to produce the *plan* that will be used as the input for future 'Feature Requests'. 
        
        ## 🎯 Expected Output Format
        The plan should conclude with a **"Next Steps: Feature Requests for Implementation"** section containing copy-paste ready GitHub issue templates. This is the most valuable deliverable - actionable next steps that can be immediately converted to implementation tasks.
        
        **Example Format:**
        ```
        ### Phase 1: Foundation
        **1. Create Authentication System**
        ```
        Title: Implement OAuth2 authentication with GitHub
        Description: Set up user authentication using OAuth2 flow with GitHub integration
        Deliverables: Login/logout functionality, user session management, protected routes
        ```
        
        **2. Set up Database Schema**
        ...etc
        ```
        
        Implementation will happen in separate pull requests using these feature requests as specifications.