name: "🐛 Bug Report"
description: "Create a report to help us improve"
title: "bug: [Short description of the bug]"
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: "Thank you for taking the time to fill out this bug report! Providing clear details will help us resolve the issue much faster."

  - type: textarea
    id: bug-description
    attributes:
      label: "Describe the bug"
      description: "A clear and concise description of what the bug is."
      placeholder: "When I run the daily data pipeline, it fails with a KeyError when processing player stats."
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "Please provide the exact steps to reproduce the behavior."
      value: |
        1. Checked out commit `[commit hash]`
        2. Ran the command `...`
        3. Scrolled down to `...`
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: "Expected Behavior"
      description: "A clear and concise description of what you expected to happen."
      placeholder: "I expected the pipeline to complete successfully and write a new file to S3."
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: "Relevant Log Output"
      description: "Please copy and paste any relevant log output or error messages. This will be automatically formatted into a code block."
      render: shell

  - type: textarea
    id: environment
    attributes:
      label: "Environment"
      description: "Please provide any relevant details about the execution environment."
      placeholder: |
        - Application: [e.g., data-pipeline]
        - OS: [e.g., Ubuntu 22.04 on a GitHub Actions runner]
        - Python Version: [e.g., 3.12.2]
    validations:
      required: false
