name: 'Setup Python and Poetry'
description: 'Sets up Python, installs Poetry, and configures caching'
inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.12'
  working-directory:
    description: 'Directory to cache dependencies for'
    required: false
    default: '.'
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: latest
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Cache Poetry dependencies
      uses: actions/cache@v3
      with:
        path: ${{ inputs.working-directory }}/.venv
        key: poetry-${{ runner.os }}-${{ inputs.working-directory }}-${{ hashFiles(format('{0}/poetry.lock', inputs.working-directory)) }}
        restore-keys: |
          poetry-${{ runner.os }}-${{ inputs.working-directory }}-
